### PR TITLE
Migrate dependency `toml` to `tomllib`

### PR DESCRIPTION
**Pull request by Contextualist**
Reasons for the migration:

1. [`hukkin/tomli`](https://github.com/hukkin/tomli) has been accepted as part of the Python standard library (see [PEP680](https://www.python.org/dev/peps/pep-0680/)), named as [`tomllib`](https://docs.python.org/3/library/tomllib.html), and it is available since Python 3.11.
2. [`uiri/toml`](https://github.com/uiri/toml) has not been active since 2020, while `hukkin/tomli` is an actively maintained implementation of TOML 1.0 spec, with 100% test coverage.

### CODE REVIEW

**Comment by coltonbh** [comment]
Keen eye on the `hukkin/tomli` library--it appears this will indeed be better supported since it is the official library added to the standard library. Thanks :)

Let's keep the python 3.11 checks and if/else import statements out. That adds complexity and would require a multi-python-version testing environment which we'll want to avoid. Juice ain't worth the squeeze. This is a very simple feature--just read/write a toml file, we don't want to add complexity to the package to save a tiny package install for 3.11 users.

For merge see my review comments in the code, specifically:

1. Remove python3.11 checks and just install `tomli` and `tomli_w` for all python versions.
2. Don't alias the import
3. Fix file read/write using "b" (binary) mode, these are text files, not binary.

Thanks for the maintenance! Any questions lemme know ❤️

**Comment by Contextualist** [comment]
Thanks for the quick review!

> Let's keep the python 3.11 checks and if/else import statements out.

I am following the suggestions from the authors ([here](https://github.com/hukkin/tomli#building-a-tomlitomllib-compatibility-layer) and [here](https://github.com/hukkin/tomli/issues/219#issuecomment-1512055936)) for the compatibility layer. I would say that it's OK to trust the maintainer for the consistency between `tomllib` and `hukkin/tomli`, but it would also be OK to always install `tomli` until we no longer need to support Python < 3.11, though.

> Fix file read/write using "b" (binary) mode, these are text files, not binary.

Binary mode is [required by the `tomllib` interface](https://github.com/hukkin/tomli#parse-a-toml-file), in order to enforce UTF-8 encoding as part of the TOML spec compliance.

Let me know your decisions and I will make one final squash commit.

**Comment by coltonbh** [comment]
Thanks for the links to the documentation! 

Ok I'm persuaded by the compatibility layer for 3.11 and the `rb` mode. The `rb` is very surprising. I've never seen that for text file formats before.

So to finish this up we need a to add a 3.11 environment to the CI GitHub pipeline to ensure correctness and functionality for python 3.11+. 

Let's finish up with this:
1. Change the `tests` workflow in `test.yaml` to use a matrix of python versions and include 3.8 and 3.11 in the matrix so our tests run on both versions. (google matrix tests for GitHub actions to see how this is done).
2. Add a node inside the `CHANGELOG.md` under ## Unreleased ### Changed that notes the changes you made.
3. Squash commits.

I'll take it from there and merge and release a new version.

Thank you!

**Comment by coltonbh** [comment]
Also, please rebase from `master` as I've updated GitHub actions to run on pull requests from forked repos. Thanks!

**Comment by Contextualist** [comment]
Done! Let me know if there is any additional concern.

**Comment by coltonbh** [comment]
Very professional! Looks great! Congrats on your first PR contribution ☺️

**Comment by coltonbh** [comment]
Released to PyPi as `v0.8.3`. Thanks, @Contextualist .

**Pull request merged**
