### PR TITLE
Added py.typed file to enable type checking in projects that use chemcloud

### PR DESCRIPTION
**Pull request by jevandezande**

### CODE REVIEW

**Comment by coltonbh** [comment]
Thanks, @jevandezande . Forgot to include this! Will ship a new release now...

**Review by coltonbh — APPROVED** [review]
Thanks @jevandezande for the PR!

**Comment by coltonbh** [comment]
@jevandezande You should also be aware I just made a minor breaking change. I renamed `Molecule` to `Structure` and the associated methods on objects that refer to `.molecule` are updated to `.structure`. I've included a small backwards compatibility layer with depreciation warnings, so everything should still work, but FYI. This got released last night with a new `ChemCloud Server` and `BigChem` that also support this change. Docker containers are built and available on Docker Hub, so a redeploy for your system should be straightforward :)

**Comment by coltonbh** [comment]
[Published](https://pypi.org/project/chemcloud/#history) as `0.10.1`

**Comment by jevandezande** [comment]
@coltonbh, that breaking change was what prompted this. I agree with the name change, and it was an easy update. Thanks.

**Comment by coltonbh** [comment]
Great thanks! Yes--I'll try to make as few breaking changes as possible especially now that other people are using the project... This change felt important as I'm getting into some catalysis work and it became obvious that the `Molecule` object was often a superstructure of many molecules and not really a `Molecule` itself. I'll be adding code for fragments and such in the future and wanted to start adjusting the nomenclature to be in harmony with this.

Thanks!

**Pull request merged**
