### PR TITLE
Bump dependency versions

### PR DESCRIPTION
**Pull request by jevandezande**
The `pytest-httpx` version was conflicting with `httpx` when attempting to build with Python 3.11, so the limit was relaxed. Python was also bumped to help satisfy Poetry dependency solving ([end of security fixes for Python 3.8 is 2024-10](https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions), while end of full support for Python 3.10 is 2023-04-05)

Also bumped the `ruff` version and made it take care of the formatting and sorting, so that `isort` and `black` can be dropped. It appears that import sorting with `qcio` and `tests` as known-first-party packages was not happening, thus the import order changes.

This solves #65. However, it may be useful to bump or relax some of the dependency specifications further.

### CODE REVIEW

**Comment by coltonbh** [comment]
Thanks for this! Was out of the office this week and just getting back tonight. Will take a look Monday :)

**Review by coltonbh — CHANGES_REQUESTED** [review]
Ok! Very much like where this is headed. Thank you.

Two small changes I'd like to make:

1. Can we continue to support `python 3.9`? `3.9` is supported until almost the end of 2025 and given that the scientific community usually has very outdated machines I'd like to maintain support for older Python versions as long as we can (but not after they die). I'm fine dropping `3.8` a  few months early :) Was there a specific difficulty with keeping `3.9` supported?
2. Is there a setting/configuration flag we can use with `ruff` to maintain the former isort order of packages? I.e., 
```python
import python_std_library_pkg

import third_party_pkg 

import my_library_pkg
```

I like this import order for quick clarity on where various imports are coming from.

Happy to drop `black` and `isort`. Big thanks for this!

**Review by coltonbh — COMMENTED** [review]
Oh! And please add a quick entry to the `CHANGELOG.md` file summarizing the changes. Would like to include that mental note with the merge. 🙏

**Comment by jevandezande** [comment]
I can make the requested changes tomorrow. I think that the change in sort order with qcio is actually due to the fact that isort wasn't getting the known first party flag for qcio, and now ruff is recognizing the flag. Should I just drop that flag then if we want to sort qcio as a third party import?

**Comment by coltonbh** [comment]
Great thanks!

Usually `isort` does the following:

```python
# Standard Library Imports
import os
import sys

# Third-Party Imports
import numpy as np
from qcio import Structure

# First-Party Imports
from my_project import my_module
```

`qcio` is a third party package, external to `chemcloud`, so we'll want it with the other third party imports :)

Yes--I now see that you specifically included `qcio` as `known-first-party` which is why the sort order got changed on a few modules. Let's drop that so `qcio` is properly treated as third party. 

If you can rebase and squash your changes down to a single commit that would be great!

**Comment by coltonbh** [comment]
It would also be nice if you enabled workflows for this fork so we can confirm the updates to CI/CD are working nicely :)

Enable Workflows in the Fork:

- Navigate to your forked repository on GitHub.
- Click on the “Actions” tab.
- If workflows are not enabled, you will see a message saying "Workflows aren’t being run on this forked repository."
- Click the "Enable" button to activate GitHub Actions for your fork.

**Comment by jevandezande** [comment]
Mypy was acting weird in python3.9 on `chemcloud/config.py`, claiming that there was an attempt to union types with a `|`, despite no such line existing. I fixed the error by adding a `from __future__ import annotations`, and all the tests passed. I'm not particularly happy with this fix, since I'm unsure of the origin of the problem, but the code passes all of the tests and should be good to merge.

**Comment by coltonbh** [comment]
Looks great! Thanks @jevandezande :)

**Review by coltonbh — APPROVED** [review]
Looks great! Thanks @jevandezande :)

**Comment by coltonbh** [comment]
@jevandezande these changes have been released in `v0.12.0`. Not published to PyPi. Thanks for the update! :pray:

**Pull request merged**
